services:
  api:
    build:
      context: .
    container_name: fastapi-app
#    develop:
#      watch:
#        - action: rebuild
#          path: ./app
#        - action: rebuild
#          path: requirements.txt
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    image: postgres:16.1-alpine3.19
    container_name: db-app
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./dev.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
volumes:
  data:

